// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amkfedsjcjdqgwbfwitt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFta2ZlZHNqY2pkcWd3YmZ3aXR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk5MDUwNjIsImV4cCI6MjA4NTQ4MTA2Mn0.pq8E9KuCFRnEoH4PJrjm7XK-Q45n_J-b_ijAvKTIPkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});